name: pwrflw-hpc
channels:
  - defaults
  - conda-forge
  - https://software.repos.intel.com/python/conda

dependencies:
  # Core Python + conda‑managed packages
  - python=3.12
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates=2025.4.26
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.12.10
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - expat=2.7.0
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=9.2.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5=1.21.3
  - libffi=3.4.6
  - liblzma=5.8.1
  - libsodium=1.0.20
  - libsqlite=3.50.0
  - libzlib=1.3.1
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl=3.5.0
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyzmq=26.4.0
  - setuptools=80.8.0
  - six=1.17.0
  - sqlite=3.50.0
  - stack_data=0.6.3
  - tk=8.6.13
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xz=5.8.1
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib=1.3.1
  - pip

  # pip‑only packages
  - pip:
      - blosc2==3.3.4
      - certifi==2025.4.26
      - charset-normalizer==3.4.2
      - contourpy==1.3.2
      - cycler==0.12.1
      - deepdiff==8.5.0
      - fonttools==4.58.1
      - geojson==3.2.0
      - h5py==3.13.0
      - idna==3.10
      - kiwisolver==1.4.8
      - llvmlite==0.44.0
      - lxml==5.4.0
      - matplotlib==3.10.3
      - msgpack==1.1.0
      - ndindex==1.10.0
      - networkx==3.5
      - numba==0.61.2
      - numexpr==2.10.2
      - numpy==2.2.6
      - orderly-set==5.4.1
      - pandapower==3.1.1
      - pandas==2.2.3
      - pillow==11.2.1
      - py-cpuinfo==9.0.0
      - pyparsing==3.2.3
      - pytz==2025.2
      - requests==2.32.3
      - scipy==1.15.3
      - tables==3.10.2
      - tqdm==4.67.1
      - tzdata==2025.2
      - urllib3==2.4.0
