name: urbs
channels:
  - conda-forge
dependencies:
  - asttokens=3.0.0
  - bzip2=1.0.8
  - ca-certificates
  - colorama=0.4.6
  - comm=0.2.2
  - cpython=3.10.17
  - debugpy=1.8.14
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - importlib-metadata=8.7.0
  - ipykernel=6.29.5
  - ipython=8.36.0
  - jedi=0.19.2
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - krb5
  - libffi  # no version pinned
  - libsodium=1.0.20
  - matplotlib-inline=0.1.7
  - nest-asyncio=1.6.0
  - openssl
  - packaging=25.0
  - parso=0.8.4
  - pickleshare=0.7.5
  - pip
  - platformdirs=4.3.8
  - prompt-toolkit=3.0.51
  - psutil=7.0.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - python=3.10  # do not pin patch version
  - python-dateutil=2.9.0.post0
  - python_abi=3.10
  - pyzmq=26.4.0
  - setuptools
  - six=1.17.0
  - sqlite  # no version pinned
  - stack_data=0.6.3
  - tk  # no version pinned
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing_extensions=4.13.2
  - wcwidth=0.2.13
  - wheel
  - xz
  - zeromq=4.3.5
  - zipp=3.22.0
  - zlib
  - pip:
      - blosc2==2.0.0
      - cycler==0.12.1
      - cython==3.1.1
      - fonttools==4.58.1
      - h5py==3.13.0
      - highspy==1.10.0
      - joblib==1.5.1
      - kiwisolver==1.4.8
      - matplotlib==3.5.2
      - msgpack==1.1.0
      - networkx==3.4.2
      - numexpr==2.10.2
      - numpy==1.26.4
      - pandas==2.2.3
      - pillow==11.2.1
      - ply==3.11
      - py-cpuinfo==9.0.0
      - pyomo==6.9.2
      - pyparsing==3.2.3
      - pytz==2025.2
      - scikit-learn==1.6.1
      - scipy==1.15.3
      - tables==3.8.0
      - threadpoolctl==3.6.0
      - tqdm==4.67.1
      - tsam==2.3.6
      - tzdata==2025.2
